package Vista.formulario_empleado.Registro;

import Negocio.Control.Empleado;
import Vista.formulario_empleado.Negocio.Modelo.Control;

import java.awt.BorderLayout ; 
import java.awt.Image;
import static java.awt.SystemColor.control;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author CINTHIA FELIPE
 */
public class InterfazFormulario extends javax.swing.JFrame {
    javax.swing.ImageIcon icono= new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/ticket.png"));
   //JScrollPane pane = new JScrollPane(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
   //this.setContentPane(pane);

    Control control = new Control();
    private Object lblFoto;
    public InterfazFormulario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNombre = new javax.swing.JLabel();
        JLApellidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        JLSexo = new javax.swing.JLabel();
        JLFechaNacimiento = new javax.swing.JLabel();
        JCBTipoDocumento = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JLNroDocumento = new javax.swing.JLabel();
        JLDireccion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JCBDepartamento = new javax.swing.JLabel();
        JCBProvincia = new javax.swing.JLabel();
        JLDireccion2 = new javax.swing.JLabel();
        txtDireccion2 = new javax.swing.JTextField();
        cDepartamento = new java.awt.Choice();
        cProvincia = new java.awt.Choice();
        JLNroTelefono = new javax.swing.JLabel();
        JLNroCelular = new javax.swing.JLabel();
        JLCorreo = new javax.swing.JLabel();
        JLNacionalidad = new javax.swing.JLabel();
        JLPeriodoPrueba = new javax.swing.JLabel();
        JCBEstado = new javax.swing.JLabel();
        JCBSeccion = new javax.swing.JLabel();
        JCBCargo = new javax.swing.JLabel();
        JLFechaIngreso = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        JCBMasculino = new javax.swing.JCheckBox();
        JCBFemenino = new javax.swing.JCheckBox();
        cTipoDocumento = new java.awt.Choice();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtNroDocumento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        cSeccion = new java.awt.Choice();
        cCargo = new java.awt.Choice();
        txtFechaIngreso = new javax.swing.JTextField();
        cEstado = new java.awt.Choice();
        BotonGuardar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        cPeriodoPrueba = new java.awt.Choice();
        JScrollMenu = new javax.swing.JScrollBar();
        BotonMostrar = new javax.swing.JButton();
        jlbFoto = new javax.swing.JLabel();
        btnCargarFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(204, 255, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLNombre.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLNombre.setForeground(new java.awt.Color(0, 41, 191));
        JLNombre.setText("Nombre");

        JLApellidos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLApellidos.setForeground(new java.awt.Color(0, 41, 191));
        JLApellidos.setText("Apellidos");

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        JLSexo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLSexo.setForeground(new java.awt.Color(0, 41, 191));
        JLSexo.setText("Sexo");

        JLFechaNacimiento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLFechaNacimiento.setForeground(new java.awt.Color(0, 41, 191));
        JLFechaNacimiento.setText("Fecha de Nacimiento");

        JCBTipoDocumento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBTipoDocumento.setForeground(new java.awt.Color(0, 41, 191));
        JCBTipoDocumento.setText("Tipo de Documento de Identidad");

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro de Empleado");

        JLNroDocumento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLNroDocumento.setForeground(new java.awt.Color(0, 41, 191));
        JLNroDocumento.setText("Nro Documento");

        JLDireccion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLDireccion.setForeground(new java.awt.Color(0, 41, 191));
        JLDireccion.setText("Direccion");

        JCBDepartamento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBDepartamento.setForeground(new java.awt.Color(0, 41, 191));
        JCBDepartamento.setText("Departamento");

        JCBProvincia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBProvincia.setForeground(new java.awt.Color(0, 41, 191));
        JCBProvincia.setText("Provincia");

        JLDireccion2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLDireccion2.setForeground(new java.awt.Color(0, 41, 191));
        JLDireccion2.setText("Direccion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBDepartamento)
                    .addComponent(JCBProvincia)
                    .addComponent(JLDireccion2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cProvincia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(cDepartamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JCBDepartamento))
                    .addComponent(cDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBProvincia)
                    .addComponent(cProvincia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLDireccion2)
                    .addComponent(txtDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        JLNroTelefono.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLNroTelefono.setForeground(new java.awt.Color(0, 41, 191));
        JLNroTelefono.setText("Nro Telefono Domicilio");

        JLNroCelular.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLNroCelular.setForeground(new java.awt.Color(0, 41, 191));
        JLNroCelular.setText("Nro Celular");

        JLCorreo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLCorreo.setForeground(new java.awt.Color(0, 41, 191));
        JLCorreo.setText("Correo Electronico");

        JLNacionalidad.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLNacionalidad.setForeground(new java.awt.Color(0, 41, 191));
        JLNacionalidad.setText("Nacionalidad");

        JLPeriodoPrueba.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLPeriodoPrueba.setForeground(new java.awt.Color(0, 41, 191));
        JLPeriodoPrueba.setText("Periodo de Prueba");

        JCBEstado.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBEstado.setForeground(new java.awt.Color(0, 41, 191));
        JCBEstado.setText("Estado");

        JCBSeccion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBSeccion.setForeground(new java.awt.Color(0, 41, 191));
        JCBSeccion.setText("Seccion");

        JCBCargo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBCargo.setForeground(new java.awt.Color(0, 41, 191));
        JCBCargo.setText("Cargo");

        JLFechaIngreso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JLFechaIngreso.setForeground(new java.awt.Color(0, 41, 191));
        JLFechaIngreso.setText("Fecha de Ingreso");

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        JCBMasculino.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBMasculino.setForeground(new java.awt.Color(0, 41, 191));
        JCBMasculino.setText("Masculino");
        JCBMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBMasculinoActionPerformed(evt);
            }
        });

        JCBFemenino.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        JCBFemenino.setForeground(new java.awt.Color(0, 41, 191));
        JCBFemenino.setText("Femenino");

        txtNroDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroDocumentoKeyTyped(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });

        txtNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacionalidadKeyTyped(evt);
            }
        });

        txtFechaIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaIngresoKeyTyped(evt);
            }
        });

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonMostrar.setText("Mostrar");
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });

        jlbFoto.setText("foto");

        btnCargarFoto.setText("CargarFoto");
        btnCargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCBTipoDocumento)
                                    .addComponent(JLNroDocumento))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLFechaNacimiento)
                                    .addComponent(JLApellidos)
                                    .addComponent(JLSexo))
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 91, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(JCBMasculino)
                                                        .addGap(51, 51, 51)
                                                        .addComponent(JCBFemenino))
                                                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(105, 105, 105))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCargarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                .addGap(39, 39, 39))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLNroTelefono)
                                    .addComponent(JLNroCelular)
                                    .addComponent(JLCorreo)
                                    .addComponent(JLNacionalidad)
                                    .addComponent(JCBSeccion)
                                    .addComponent(JCBCargo)
                                    .addComponent(JLFechaIngreso)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BotonGuardar)
                                        .addComponent(JLPeriodoPrueba)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cPeriodoPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(JCBEstado)
                                                .addGap(28, 28, 28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                    .addComponent(cCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTelefono)
                                            .addComponent(txtCelular)
                                            .addComponent(txtCorreo)
                                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(BotonLimpiar)
                                                .addGap(43, 43, 43)))
                                        .addGap(107, 107, 107)
                                        .addComponent(BotonSalir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonMostrar))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLDireccion)
                                .addGap(107, 107, 107)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(JLNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(JScrollMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jlbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCargarFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(JCBTipoDocumento))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLFechaNacimiento))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLSexo))
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)
                                .addGap(19, 19, 19)
                                .addComponent(JLNombre)
                                .addGap(18, 18, 18)
                                .addComponent(JLApellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JCBMasculino)
                                .addComponent(JCBFemenino))
                            .addComponent(cTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNroDocumento)
                    .addComponent(txtNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLDireccion)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNroTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNroCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNacionalidad)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cPeriodoPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLPeriodoPrueba)
                        .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JCBEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLFechaIngreso)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBSeccion)
                    .addComponent(cSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBCargo)
                    .addComponent(cCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonLimpiar)
                    .addComponent(BotonSalir)
                    .addComponent(BotonMostrar))
                .addContainerGap())
            .addComponent(JScrollMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void JCBMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBMasculinoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FondoFormulario AplicarFondo = new FondoFormulario();
        this.add( AplicarFondo, BorderLayout.SOUTH );
        AplicarFondo.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed
//limpia las casillas al presionar el boton LIMPIAR en caso de error al ingresar los datos
    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        txtNombre.setText("");
        txtApellido.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        txtDireccion2.setText("");
        txtFechaIngreso.setText("");
        txtFechaNacimiento.setText("");
        txtNacionalidad.setText("");
        txtNroDocumento.setText("");
        txtTelefono.setText("");      
    }//GEN-LAST:event_BotonLimpiarActionPerformed
//Los campos que estan aqui tienen que ser llenados obligatoriamente, caso contrario nose guardara
    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nombre");
            return;
        }
        if(txtApellido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Apellido");
            return;
        }
        if(txtCelular.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese en Nro de Celular");
            return;
        }
        if(txtCorreo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Correo");
            return;
        }
        if(txtDireccion2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor Ingrese su Direccion");
            return;
        }
        if(txtFechaIngreso.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Fecha de Ingreso");
            return;
        }
        if(txtFechaNacimiento.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Fecha de Nacimiento");
            return;
        }
        if(txtNacionalidad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese la Nacionalidad");
            return;
        }
        if(txtNroDocumento.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el Nro de Documento");
            return;
        }
        
        //respuesta de los datos bien ingresados
        Empleado empleado= new Empleado();
        //Empleado empleado= new Empleado(String Nombre,String Apellido,String Sexo,String TipoDeDocumento,String NroDocumento, String Direccion,
          //                         String Departamento, String Provincia,String Direccion2, String NroTelefono,String NroCelular,String Correo,
            //                       String Nacionalidad, String PeriodoPrueba,String Estado,String FechaIngreso,String Seccion,String Cargo,String Categoria);
        control.GuardarEmpleado(empleado);
        
  
    }//GEN-LAST:event_BotonGuardarActionPerformed
//define el tipo de caracter y tamaño a llenar en cada casilla 
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if(txtNombre.getText().length()>=12){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        if(txtApellido.getText().length()>=25){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNroDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDocumentoKeyTyped
       if(txtNroDocumento.getText().length()>=8){
           evt.consume();
       }
        char TipoDeTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNroDocumentoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        if(txtTelefono.getText().length()>=8){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        if(txtCelular.getText().length()>=8){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        if(txtCorreo.getText().length()>=20){
            evt.consume();
        }
        char TipoDeTecla=evt.getKeyChar();
                       //(^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+
                //(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$;
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacionalidadKeyTyped
        if(txtNacionalidad.getText().length()>=15){
            evt.consume();
        }
        char TipoDeTecla= evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNacionalidadKeyTyped

    private void txtFechaIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaIngresoKeyTyped
        if(txtFechaIngreso.getText().length()>=8){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaIngresoKeyTyped

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(txtNombre.getText().length()>=2){
            JLImagenNombre.setIcon(icono);
        }else{
            JLImagenNombre.setIcon(null);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        JOptionPane.showMessageDialog(null,control.MostrarControl());
    }//GEN-LAST:event_BotonMostrarActionPerformed

    File fichero;
    private void btnCargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarFotoActionPerformed
        int resultado;
        CargarFoto ventana = new CargarFoto();
        ventana.setVisible(true);
        FileNameExtensionFilter filtro= new FileNameExtensionFilter( "JPG y PNG","jpg","png");
        ventana.jfchCargarFoto2.setFileFilter(filtro);
        resultado= ventana.jfchCargarFoto2.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado){
            File fichero = ventana.jfchCargarFoto2.getSelectedFile();
            try{
                ImageIcon icon = new ImageIcon(fichero.toString());
                Icon icono= new
                ImageIcon(icon.getImage().get ScaledInstance(jlbFoto.getWidth(), jlbFoto.getHeight(), Image.SCALE_DEFAULT));
                jlbFoto.setIcon(icono);
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, "error al abrir la imagen" + ex);

            }
            jlbFoto.setText(null);
        }
    }//GEN-LAST:event_btnCargarFotoActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel JCBCargo;
    private javax.swing.JLabel JCBDepartamento;
    private javax.swing.JLabel JCBEstado;
    private javax.swing.JCheckBox JCBFemenino;
    private javax.swing.JCheckBox JCBMasculino;
    private javax.swing.JLabel JCBProvincia;
    private javax.swing.JLabel JCBSeccion;
    private javax.swing.JLabel JCBTipoDocumento;
    private javax.swing.JLabel JLApellidos;
    private javax.swing.JLabel JLCorreo;
    private javax.swing.JLabel JLDireccion;
    private javax.swing.JLabel JLDireccion2;
    private javax.swing.JLabel JLFechaIngreso;
    private javax.swing.JLabel JLFechaNacimiento;
    private javax.swing.JLabel JLNacionalidad;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLNroCelular;
    private javax.swing.JLabel JLNroDocumento;
    private javax.swing.JLabel JLNroTelefono;
    private javax.swing.JLabel JLPeriodoPrueba;
    private javax.swing.JLabel JLSexo;
    private javax.swing.JScrollBar JScrollMenu;
    private javax.swing.JButton btnCargarFoto;
    private java.awt.Choice cCargo;
    private java.awt.Choice cDepartamento;
    private java.awt.Choice cEstado;
    private java.awt.Choice cPeriodoPrueba;
    private java.awt.Choice cProvincia;
    private java.awt.Choice cSeccion;
    private java.awt.Choice cTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbFoto;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion2;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroDocumento;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void ScaledInstance(int width, int height, int SCALE_DEFAULT) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
